version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tautulli_web_1
      APP_PORT: 8181

  web:
    image: lscr.io/linuxserver/tautulli:2.12.5@sha256:9c7d9322e0880c7e1271bb31165123205773b4d015df1bf19b130d8d4ff00901
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
