version: "3.7"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    ports:
      - "1180:80"
      - "1443:443"
    volumes:
      - ${APP_DATA_DIR}/stacks:/appsmith-stacks
    restart: on-failure