version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: deluge_server_1
      APP_PORT: 8112

  server:
    image: linuxserver/deluge:2.1.1
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
