version: "3.7"

services:
  server:
    image: linuxserver/mylar3:0.6.9@sha256:5925054dfed093cfe9617077cb8f8d995354485d0a8d7222d01f739ef0e2dda1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/comics:/comics
      - ${APP_DATA_DIR}/data/downloads:/downloads
    ports:
      - 8880:8090