version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: projectsend
      APP_PORT: 80

  server:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data:/data
    environment:
      - MAX_UPLOAD=5000000
    restart: on-failure
    links:
      - localhost

  localhost:
    image: mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd
    restart: on-failure
    stop_grace_period: "1m"
    volumes:
      - "${APP_DATA_DIR}/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "projectsend"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
